-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-11-03 09:21:23 SGT
--   site:      DB2/UDB 7.1
--   type:      DB2/UDB 7.1



CREATE TABLE ADMIN 
    (
     ID_Admin CHAR (6) NOT NULL , 
     Nama_Admin VARCHAR (25) NOT NULL , 
     Password VARCHAR NOT NULL 
    )
;

ALTER TABLE ADMIN ADD CONSTRAINT ADMIN_PK PRIMARY KEY (ID_Admin)
;

CREATE TABLE Drum 
    (
     ID_Kursus CHAR (6) NOT NULL , 
     Materi_Kursus_Drum VARCHAR (20) NOT NULL 
    )
;

ALTER TABLE Drum ADD CONSTRAINT Drum_PK PRIMARY KEY (ID_Kursus)
;

CREATE TABLE Gitar 
    (
     ID_Kursus CHAR (6) NOT NULL , 
     Tipe_Kursus_Gitar VARCHAR (15) NOT NULL 
    )
;

ALTER TABLE Gitar ADD CONSTRAINT Gitar_PK PRIMARY KEY (ID_Kursus)
;

CREATE TABLE INSTRUKTUR 
    (
     ID_Instruktur CHAR (6) NOT NULL , 
     Nama_Instruktur VARCHAR (25) NOT NULL , 
     Bidang_Musik VARCHAR (20) NOT NULL , 
     ADMIN_ID_Admin CHAR (6) NOT NULL , 
     INSTRUKTUR_ID_Instruktur CHAR (6) NOT NULL 
    )
;

ALTER TABLE INSTRUKTUR ADD CONSTRAINT INSTRUKTUR_PK PRIMARY KEY (ID_Instruktur)
;

CREATE TABLE Keyboard 
    (
     ID_Kursus CHAR (6) NOT NULL , 
     Jenis_Kursus_Keyboard VARCHAR (20) NOT NULL 
    )
;

ALTER TABLE Keyboard ADD CONSTRAINT Keyboard_PK PRIMARY KEY (ID_Kursus)
;

CREATE TABLE KURSUS_MUSIK 
    (
     ID_Kursus CHAR (6) NOT NULL , 
     Jumlah_Siswa VARCHAR (50) NOT NULL , 
     INSTRUKTUR_ID_Instruktur CHAR (6) NOT NULL 
    )
;
CREATE UNIQUE INDEX KURSUS_MUSIK__IDX
    ON KURSUS_MUSIK 
    ( 
     INSTRUKTUR_ID_Instruktur ASC 
    ) 
    PCTFREE 10 
    DISALLOW REVERSE SCANS 
;

ALTER TABLE KURSUS_MUSIK ADD CONSTRAINT KURSUS_MUSIK_PK PRIMARY KEY (ID_Kursus)
;

CREATE TABLE SISWA 
    (
     ID_Siswa CHAR (6) NOT NULL , 
     Nama_Siswa VARCHAR (25) NOT NULL , 
     ADMIN_ID_Admin CHAR (6) NOT NULL , 
     Jenis_Kelamin VARCHAR (20) NOT NULL , 
     KURSUS_MUSIK_ID_Kursus CHAR (6) NOT NULL 
    )
;

ALTER TABLE SISWA ADD CONSTRAINT SISWA_PK PRIMARY KEY (ID_Siswa)
;

ALTER TABLE Drum
    ADD CONSTRAINT Drum_KURSUS_MUSIK_FK FOREIGN KEY
    ( 
     ID_Kursus
    ) 
    REFERENCES KURSUS_MUSIK 
    ( 
     ID_Kursus
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE Gitar
    ADD CONSTRAINT Gitar_KURSUS_MUSIK_FK FOREIGN KEY
    ( 
     ID_Kursus
    ) 
    REFERENCES KURSUS_MUSIK 
    ( 
     ID_Kursus
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE INSTRUKTUR
    ADD CONSTRAINT INSTRUKTUR_ADMIN_FK FOREIGN KEY
    ( 
     ADMIN_ID_Admin
    ) 
    REFERENCES ADMIN 
    ( 
     ID_Admin
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE INSTRUKTUR
    ADD CONSTRAINT INSTRUKTUR_INSTRUKTUR_FK FOREIGN KEY
    ( 
     INSTRUKTUR_ID_Instruktur
    ) 
    REFERENCES INSTRUKTUR 
    ( 
     ID_Instruktur
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE Keyboard
    ADD CONSTRAINT Keyboard_KURSUS_MUSIK_FK FOREIGN KEY
    ( 
     ID_Kursus
    ) 
    REFERENCES KURSUS_MUSIK 
    ( 
     ID_Kursus
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE KURSUS_MUSIK
    ADD CONSTRAINT KURSUS_MUSIK_INSTRUKTUR_FK FOREIGN KEY
    ( 
     INSTRUKTUR_ID_Instruktur
    ) 
    REFERENCES INSTRUKTUR 
    ( 
     ID_Instruktur
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE SISWA
    ADD CONSTRAINT SISWA_ADMIN_FK FOREIGN KEY
    ( 
     ADMIN_ID_Admin
    ) 
    REFERENCES ADMIN 
    ( 
     ID_Admin
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE SISWA
    ADD CONSTRAINT SISWA_KURSUS_MUSIK_FK FOREIGN KEY
    ( 
     KURSUS_MUSIK_ID_Kursus
    ) 
    REFERENCES KURSUS_MUSIK 
    ( 
     ID_Kursus
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE ALIAS                             0
-- CREATE BUFFERPOOL                        0
-- CREATE DATABASE                          0
-- CREATE DISTINCT TYPE                     0
-- CREATE INSTANCE                          0
-- CREATE NODE GROUP                        0
-- CREATE TABLESPACE                        0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
